name: Push image

on:
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: push-step
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: yorinasub17/gitea-release-resource:latest,yorinasub17/gitea-release-resource:${{ github.event.release.tag_name }}
      - uses: sigstore/cosign-installer@main
      - name: Sign the images
        run: |
          cosign sign yorinasub17/gitea-release-resource@${{ steps.push-step.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: 1
